### ISSUE TITLE
Unable to use obonet on both python 2.7 and 3.6

### ISSUE THREAD

**Issue by PetrovskYYY** [dhimmel/obonet#9] opened 2017-11-20 09:29 UTC
Platform: Windows 10 (64 bit)
Using python 3.6.1 during installation I get the following errors:
```
C:\Windows\system32>pip install obonet
Collecting obonet
  Using cached obonet-0.2.2.tar.gz
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 13: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 13: invalid continuation byte
``` 
other packages install normally

with python 2.7 everything installs without problems, but during runtime I get the following error:
```
Traceback (most recent call last):
  File "D:\Petrovskiy\Documents\Projects\Xpansa\is-anl\ANL-NERProcessor\src\ontologyExtraction\HP\test.py", line 2, in <module>
    import obonet
  File "C:\Program Files\Python27\lib\site-packages\obonet\__init__.py", line 1, in <module>
    from .read import read_obo
  File "C:\Program Files\Python27\lib\site-packages\obonet\read.py", line 6, in <module>
    from .io import open_read_file
  File "C:\Program Files\Python27\lib\site-packages\obonet\io.py", line 5, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```

**Comment by dhimmel** [comment] 2017-11-20 11:08
Interesting. I'm not sure this is an `obonet` bug, but rather is an issue with `pip`. See

+ https://stackoverflow.com/a/41906207/4651668
+ https://stackoverflow.com/a/21190382/4651668
+ https://github.com/pypa/pip/issues/4110
+ https://github.com/pypa/pip/pull/4486

See if you can update your `pip` version or try the other listed workarounds.

Note that `obonet` doesn't support Python 2, so even though it installs for you, the code will likely error during runtime.

**Comment by dterg** [comment] 2018-03-17 20:30
I've encountered this issue for some of the obo files. The issue is if you're passing the .obo file directly as a path rather than .gz or compressed format in the open_read_file() function. If you (temporarily) replace line 25 in the read.py from:

``` obo_file = open_read_file(path_or_file) ```

to:

``` obo_file = open(path_or_file, 'r','encoding='utf8') ```

This works for me. Long-term, I think the best approach would be to detect if its a compressed file format or if its an .obo file which by default/standards uses utf-8 encoding.

**Comment by dhimmel** [comment] 2018-03-19 13:40
@dterg what error are you talking about? A `UnicodeDecodeError`? I think from your description, your issue is separate from the original issue which had to deal with an outdated pip and using obonet in Python 2 (we only officially support Python 3).

So you are saying the following line causes an error?

https://github.com/dhimmel/obonet/blob/1441dd85cfb9b96cb88a32028a29e8bfe228695a/obonet/read.py#L23

Can you paste the full error text here?

>  if you're passing the .obo file directly

What do you mean by that? Can you paste your code?

> Long-term, I think the best approach would be to detect if its a compressed file format or if its an .obo file which by default/standards uses utf-8 encoding.

Hmm. The `open_read_file` function should be smart like this:

https://github.com/dhimmel/obonet/blob/1441dd85cfb9b96cb88a32028a29e8bfe228695a/obonet/io.py#L8-L13

Therefore, I'd love to get to the bottom of this if there's an error with `open_read_file`.

**Comment by dterg** [comment] 2018-03-25 02:47
@dhimmel I looked into this and it seems it was due to settings in the python env. With a fresh installation on a new virtual environment it worked absolutely fine with the same .obo files. Thanks!

I'm running on Windows 10 64 bit (as the original poster) with no issues so I think this issue can be closed (?)

**Comment by dhimmel** [comment] 2018-03-25 15:34
> With a fresh installation on a new virtual environment it worked absolutely fine with the same .obo files.

Great!

I'll close this because I think the original comment is about a pip issue not an obonet issue.

**Closed by dhimmel** 2018-03-25 15:34 UTC
